### ISSUE TITLE
(Issue Example) Signing Off doesn't disconnect player

### ISSUE THREAD

**Issue by RainingChain** [RainingChain/rainingchain#1]
This is an issue report example.

Pressing the Sign Off button doesn't disconnect the player correctly.
Logging in again afterwards will duplicate the player.

**Comment by lifeiscontent** [comment]
@RainingChain not sure if this helps, but I think you could run a beforepageunload callback. http://stackoverflow.com/questions/14746851/execute-javascript-function-before-browser-reloads-closes-browser-exits-page

**Comment by RainingChain** [comment]
The issue itself was server side so onbeforeunload won't really help. I do use that to sign off the player because it is faster than waiting for the socket to timeout. Anyway, this was fixed months ago in v1.1.
