### ISSUE TITLE
Error connecting to replicaset instance?

### ISSUE THREAD

**Issue by aerze** [RainingChain/rainingchain#5]
So I've been trying to create a new quest, I think I'm finally getting used to your editor. 
But every once in a while when trying to restart the server I get this error.
If I wait a while, it stops happening, and I can't trace what's happening.

![raining chains mongo replica error](https://cloud.githubusercontent.com/assets/4723083/5915064/5e23f6aa-a5b5-11e4-95e7-3970307a5a7e.PNG)

**Comment by RainingChain** [comment]
Thanks for the feedback. This should be fixed in the next release. 

I might also add support to allow people to use their local database instead of the public online one.

**Comment by aerze** [comment]
Yeah if there could be a config file that I could use to point to a new that would be good. Or better yet a way to replicate a snapshot of the public one locally.
