### ISSUE TITLE
What's the minified code?

### ISSUE THREAD

**Issue by brynnb** [RainingChain/rainingchain#8]
Looking through this code base to help get an idea of how to structure my own similar project. You have this file minified: https://github.com/RainingChain/rainingchain/blob/master/server/min.js

and the main app.js entry point seems to point to a /private/ directory that doesn't exist in the repo if it exists locally. Could you comment on what's going on with this file? Just trying to understand the application flow here. Thanks!

**Comment by RainingChain** [comment]
The min file contains sensitive code related with:
-Database
-Account creation and login
-WebSocket initialization
-Quest API
